version: '3.5'

services:
  project-symfony-server-web:
    container_name: project-symfony-server-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      # punto de entrada de la app symfony
      - ./public:/appdata/www/public
    depends_on:
      - project-symfony-server-be
    networks:
      - project-symfony-server-network

  project-symfony-server-be:
    env_file:
      - ./docker/proxy.env
    container_name: project-symfony-server-be
    build:
      # Proxy configurado en el Dockerfile, no toma los archivos .env en el build
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # linux users
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - project-symfony-server-db
    networks:
      - project-symfony-server-network

  project-symfony-server-db:
    container_name: project-symfony-server-db
    build:
      context: ./docker/database
    ports:
      - 36001:3306
    environment:
      MYSQL_DATABASE: 'mprod_project-symfony'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - project-symfony-server-db-data:/var/lib/mysql
      - './docker/database/mysqld.cnf:/etc/mysql/mysqld.cnf'
    networks:
      - project-symfony-server-network

  project-symfony-phpmyadmin:
    container_name: project-symfony-server-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: project-symfony-server-db
    depends_on:
      - project-symfony-server-db
    networks:
      - project-symfony-server-network

volumes:
  project-symfony-server-db-data:

networks:
  project-symfony-server-network:
    external: true
