<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDXDMZMc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDXDMZMc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDXDMZMc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDXDMZMc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDXDMZMc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DXDMZMc',
    'container.build_id' => 'f662664f',
    'container.build_time' => 1631015172,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDXDMZMc');
